---
title: "00-Introduction"
author: "Melissa K Sharp"
date: "`r Sys.Date()`"
delete_merged_file: true
site: bookdown::bookdown_site
output:
  bookdown::gitbook:
    number_sections: false 
    includes: 
      after_body: disqus.html
bibliography: bibliography.bib
csl: apa-annotated.csl
link-citations: yes
edit: https://github.com/sharpmel/STROBECourse
---

#  Observational Studies {-}
Careful design and analysis of observational studies is essential because they are not structured to control for these external factors, thus they are especially prone to bias and confounding [@dreyer2010; @songchung2010; @hemkens2018_confounding]. In an ideal world, people would be able to use randomized control trials more often, however, sometimes it is simply unethical or impractical to conduct an RCT [@songchung2010; @scales2005]. For example, when investigating socioeconomic impacts on health or surgical procedures.
</br>

Due to the complex design and conduct of observational studies, they have been deemed to be “the most necessary and difficult” studies to conduct [@harper2019]. Observational studies are conducted in real-world settings and can investigate the impact of health policies on populations and explore the distribution of health outcomes across groups [@dreyer2010]. RCTs simply cannot achieve these same results. Observational research also allows participants to be followed for longer periods of time meaning that one can evaluate changes in health outcomes throughout the lifespan. Furthermore, observational studies affordably provide a larger number of participants in comparison to RCTs [@dreyer2010]. This allows investigations into differences between subgroups in the population (e.g., different age groups, disease subtypes) [@ligthelm2007]. Given the breadth of topics that observational studies can cover, it is no surprise that it is the most common study design used in biomedical research [@funai2001]. 
</br>

## Why STROBE? {-}
Due to a high prevalence of observational studies in biomedical research, widespread poor reporting means that an enormous amount of the medical literature has issues. Research has shown that items concerning the methodology and results of observational studies are particularly poorly reported reported [@irani2018; @jeelani2014; @kim2012; @langan2010; @papathanasiou2010; @poorolajal2011]. Details about participants, data collection methods, and analyses are common problems. Missing details on how many people were eligible to participate, consented, and lost to follow-up questions the generalizability of results. Whereas, missing data, the reliability of the data collection instruments used, how the data was analyzed, and missing disclosures of funding sources can be worrying as motives for certain narratives or results may be hidden. Therefore, a reporting guideline for observational research is critically needed to reinforce replicability and reproducibility and instill greater confidence in the trustworthiness of results. 
</br>

## What is STROBE and how can I use it? {-}
The STrengthening the Reporting of OBservational studies in Epidemiology (STROBE) Statement is a 22-item checklist that details the key information needed when reporting the results of an observational study [@vonelm2007] (Figure 1). It is also accompanied by an Explanation and Elaboration (E&E) document that provides further details for each checklist item and gives examples of good reporting [@vandenbroucke2007]. 
</br>

STROBE comes as a downloadable checklist. You can download a fillable Word checklist (or static pdf) on the [STROBE website](https://www.strobe-statement.org/index.php?id=available-checklists). There is also a [Writing Aid Tool for Microsoft] (https://github.com/carllachat/WritingAidTool) that you can download and install includes the STROBE checklist within the software. 
</br>
For detailed background and guidance on STROBE you can read the Explanation and Elaboration [@vandenbroucke2007] article. Briefly put, STROBE does not dictate *how* to conduct research nor the specific order that items should be written in (only that they should be under the relevant IMRaD heading). Some items may not be applicable to your study, just state so and explain why. STROBE is not meant to be a "procedural straightjacket", rather, think of it as a life jacket. Its structure may be helpful for study planing or peer review but it is not designed for that purpose. </br>