---
title: "FAQ"
author: "Melissa K Sharp"
output:
  bookdown::gitbook:
    includes:
      after_body: disqus.html
---

# Frequently Asked Questions (FAQ)
## How Can I Contribute? {-}
If you Know RMarkdown and GitHub you can suggests edits here: 
Otherwise, the main author is reachable via e-mail or Twitter. When contact is made via these mechanisms it will be reported as such in the documentation. 

Readers can contribute in two ways. One way is to contribute content directly, and the easiest way, is through GitHub pull requests if your book source is hosted on GitHub. Basically, any GitHub user can click the edit button on the page of an Rmd source file, edit the content, and submit the changes to you for your approval. If you are satisfied with the changes proposed (you can clearly see what exactly was changed), you can click a “Merge” button to merge the changes. If you are not satisfied, you can provide your feedback in the pull request, so the reader can further revise it according to your requirements. We mentioned the edit button in the GitBook style in Section 3.1.1. That button is linked to the Rmd source of each page, and can guide you to create the pull request. There is no need to write emails back and forth to communicate simple changes, such as fixing a typo.

Another way for readers to contribute to your book is to leave comments. Comments can be left in multiple forms: emails, GitHub issues, or HTML page comments. Here we use Disqus (see Section 4.1) as an example. Disqus is a service to embed a discussion area on your web pages, and can be loaded via JavaScript. You can find the JavaScript code after you register and create a new forum on Disqus, which looks like this:
(https://bookdown.org/yihui/bookdown/collaboration.html)

### How is the book merged/compiled? 
The book uses a "Merge and Knit" approach which runs all code chunks in all chapters in the same R session. This allows objects created in previous chapters to be used in later chapters. (https://bookdown.org/yihui/bookdown/new-session.html)

##I'm having difficulties formatting the text
The basics of text formatting in RMarkdown can be found here: 
https://bookdown.org/yihui/bookdown/markdown-syntax.html

#collabortion problems
Since all book chapters are plain-text files, they are perfect for version control tools, which means if all your co-authors and collaborators have basic knowledge of a version control tool like GIT, you can collaborate with them on the book content using these tools. In fact, collaboration with GIT is possible even if they do not know how to use GIT, because GitHub has made it possible to create and edit files online right in your web browser. Only one person has to be familiar with GIT, and that person can set up the book repository. The rest of the collaborators can contribute content online, although they will have more freedom if they know the basic usage of GIT to work locally.
(https://bookdown.org/yihui/bookdown/collaboration.html)