---
title: "03-BackgroundRationale"
author: "Melissa K Sharp"
output: html_document
---

# Item 2: Background and Rationale
3.2 – Introduction: Background/Rationale (Week 1, Module 2)
3.2.1 – STROBE
The items from STROBE state that you should report: 
•	Explain the scientific background and rationale for the investigation being reported

3.2.2 – Objectives
Topics to cover. Do your research. Cite/discuss systematic reviews if possible. Highlight the gap in research that your work is aiming to fill. 

Specific examples from QA: 
•	ME-2 Explain in the scientiﬁc background of the paper how ⁄why the speciﬁc biomarker(s) have been chosen, potentially among many others (e.g. others are studied but reported elsewhere or not studied at all)
•	STROME-ID 2.1: provide background information about the pathogen population and the distribution of pathogen strains within the host population at risk
•	SBR 2 Clarify whether simulation is subject of research or investigational method for research.
•	ROSES-I 2.1: State what is known about the kinetics of antibody rise, decay, and persistence following infection for the particular virus being studied and the justification for threshold antibody titers or changes in titers used to define evidence of infection
•	ROSES-I 2.2: State what is known about the sensitivity and specificity of the antibody detection assay being used
