---
title: "05-Setting"
author: "Melissa K Sharp"
delete_merged_file: true
site: bookdown::bookdown_site
output:
  bookdown::gitbook:
    number_sections: false 
    includes: 
      after_body: disqus.html
bibliography: bibliography.bib
csl: apa-annotated.csl
link-citations: yes
edit: https://github.com/sharpmel/STROBECourse
---

# Methods: Setting (5)
> The item from STROBE states that you should report:  
- Describe the setting, locations, and relevant dates, including periods of recruitment, exposure, follow up, and data collection  

</br></br>
**Some key items to consider adding:**</br>
- Formative research findings used to inform the study   
- Describe any characteristics of the study settings that might affect the exposures of the participants, if applicable  
</br>

## Explanation
> Readers need information on setting and locations to assess the context and generalizability of a study’s results. Exposures such as environmental factors and therapies can change over time. Also, study methods may evolve over time. Knowing when a study took place and over what period participants were recruited and followed up places the study in historical context and is important for the interpretation of results.  
</br>
Information about setting includes recruitment sites or sources (eg, electoral roll, outpatient clinic, cancer registry, or tertiary care centre). Information about location may refer to the countries, towns, hospitals or practices where the investigation took place. We advise stating dates rather than only describing the length of time periods. There may be different sets of dates for exposure, disease occurrence, recruitment, beginning and end of follow-up, and data collection. Of note, nearly 80% of 132 reports in oncology journals that used survival analysis included the starting and ending dates for accrual of patients, but only 24% also reported the date on which follow-up ended. [@altman1995; @vandenbroucke2007]

</br></br>
## Examples
- “The Pasitos Cohort Study recruited pregnant women from Women, Infant and Child clinics in Socorro and San Elizario, El Paso County, Texas and maternal-child clinics of the Mexican Social Security Institute in Ciudad Juarez, Mexico from April 1998 to October 2000. At baseline, prior to the birth of the enrolled cohort children, staff interviewed mothers regarding the household environment. In this ongoing cohort study, we target follow-up exams at 6-month intervals beginning at age 6 months.”[@goodman2005; @vandenbroucke2007]  

</br></br>
## Field-specific guidance
**Anti-microbial stewardship programs [@tacconelli2016]**  
-	Describe if setting is epidemic or endemic (high, low, medium) for the study outcome  
-	Specify type of hospital or unit and characteristics of population served by the healthcare setting  
-	Describe antimicrobial formulary in use at the study location related to the analysed antibiotics  
-	Describe infection control measures dedicated to the target resistant bacteria applied at the study location</br>

**Infectious disease molecular epidemiology [@field2014]**   
-	Clearly state the timeframe of the study; consider and appropriately reference the molecular clock of markers if known, and the natural history of the infection </br>

**Neonatal infections [@fitchett2016]**  
-	Describe the study context in terms of incidence of neonatal mortality, stillbirth, and preterm birth  
-	Describe the population included (eg, facility births, referrals from home, referrals from another facility)  
-	For community-based studies, describe care-seeking and adherence and time to referral  
-	For facility-based studies, describe obstetric care (basic or comprehensive), including proportion of births by caesarean section. Report annual number of livebirths per facility and state proportion of births in the study area that occur in hospital (vs community)  
-	For facility-based studies, indicate if the facility is public or private, and give the number of health-care staﬀ and their training. Indicate the level of neonatal care available (eg, ventilatory support, indwelling catheters) and investigations available (eg, biochemistry, radiology). Report antimicrobial guidelines used for the empiric management of neonatal sepsis  
-	State the laboratory location and capacity to process diﬀ erent sample types, and give quality control and assurance measures in place </br>

**Nutritional data [@lachat2016]**  
-	Describe any characteristics of the study settings that might affect the dietary intake or nutritional status of the participants, if applicable </br>

**Rheumatology [@zavada2014]**  
-	Provide an estimation of drug penetration in source population  
-	Describe eligibility for, and access to, treatment  
-	Outline calendar trends in availability of biologic/ awareness of outcome</br>

**Seroepidemiologic studies for influenza [@horby2017]**  
-	Describe the timing of the biological sampling in relation to the disease epidemiology in the study population (the beginning, peak, and end of virus transmission)  
-	Where known, describe the timing of biological sampling in individuals in relation to disease onset and to exposures of interest  
-	State the interval between sequential biological samples (serial cross-sectional or longitudinal studies), or specify whether only a single sample was collected (cross-sectional study)</br>

**Veterinary epidemiology [@oconnor2016]**  
-	If applicable, include information at each level of organization  

## Resources  
Do you know of any good guidance or resources related to this item? Suggest them via comments below, [Twitter](https://twitter.com/sharpmelk), [GitHub](https://github.com/sharpmel/STROBECourse), or [e-mail](mailto:melissaksharp@gmail.com).
</br> 