---
title: "07-Variables"
author: "Melissa K Sharp"
delete_merged_file: true
site: bookdown::bookdown_site
output:
  bookdown::gitbook:
    number_sections: false 
    includes: 
      after_body: disqus.html
bibliography: bibliography.bib
csl: apa-annotated.csl
link-citations: yes
edit: https://github.com/sharpmel/STROBECourse
---

# Methods: Variables (7)  
> The items from STROBE state that you should report:  
-	Clearly define all outcomes, exposures, predictors, potential confounders, and effect modifiers. Give diagnostic criteria, if applicable.  

</br>

**Some key items to consider adding:**  
-	The start and stop of any therapies or treatment  
- The mean, median, and range for each exposure group  
- The theoretical/conceptual rationale for the design of the intervention/ exposure  
-	The intervention/exposure described with sufficient detail to permit replication  
-	Description of potential confounders (other than epidemiological variables) and correlates  
-	For hypothesis-driven studies, the putative causal structure (consider a diagram like a directed acyclic graph)  
-	Sources of data and methods of assessment for each variable  
- Comparability of assessment methods among groups and over time  
-	The level of organization at which each variable was measured  
</br>
 
## Explanation  
> Authors should define all variables considered for and included in the analysis, including outcomes, exposures, predictors, potential confounders and potential effect modifiers. Disease outcomes require adequately detailed description of the diagnostic criteria. This applies to criteria for cases in a case-control study, disease events during follow-up in a cohort study and prevalent disease in a cross-sectional study.  
</br>
Clear definitions and steps taken to adhere to them are particularly important for any disease condition of primary interest in the study. For some studies, ‘determinant’ or ‘predictor’ may be appropriate terms for exposure variables and outcomes may  be called ‘endpoints’. In multivariable models, authors sometimes use ‘dependent variable’ for an outcome and ‘independent variable’ or ‘explanatory variable’ for exposure and confounding variables. The latter is not precise as it does not distinguish exposures from confounders.  
</br>
If many variables have been measured and included in exploratory analyses in an early discovery phase, consider providing a list with details on each variable in an appendix, additional table or separate publication. Of note, the International Journal of Epidemiology recently launched a new section with ‘cohort profiles’, that includes detailed information on what was measured at different points in time in particular studies. [@ebrahim2004; @walker2004] Finally, we advise that authors declare all ‘candidate variables’ considered for statistical analysis, rather than selectively reporting only those included in the final models (see also item [16a][Results: Main Results (16) ]). [@vandenbroucke2007]  

</br>

## Examples  
- “Only major congenital malformations were included in the analyses. Minor anomalies were excluded according to the exclusion list of European Registration of Congenital Anomalies (EUROCAT). If a child had more than one major congenital malformation of one organ system, those malformations were treated as one outcome in the analyses by organ system (…) In the statistical analyses, factors considered potential confounders were maternal age at delivery and number of previous parities. Factors considered potential effect modifiers were maternal age at reimbursement for antiepileptic medication and maternal age at delivery” [@artama2006; @vandenbroucke2007]

## Box 2. Matching 
In any case-control study, sensible choices need to be made on whether to use matching of controls to cases, and if so, what variables to match on, the precise method of matching to use, and the appropriate method of statistical analysis. Not to match at all may mean that the distribution of some key potential confounders (e.g., age, sex) is radically different between cases and controls. Although this could be adjusted for in the analysis there could be a major loss in statistical efficiency.  
</br>  
The use of matching in case-control studies and its interpretation are fraught with difficulties, especially if matching is attempted on several risk factors, some of which may be linked to the exposure of prime interest [@rothmanmatching1998; @szklo2000]. For example, in a case-control study of myocardial infarction and oral contraceptives nested in a large pharmaco-epidemiologic data base, with information about thousands of women who are available as potential controls, investigators may be tempted to choose matched controls who had similar levels of risk factors to each case of myocardial infarction. One objective is to adjust for factors that might influence the prescription of oral contraceptives and thus to control for <i>confounding by indication</i>. However, the result will be a control group that is <i>no longer representative</i> of the oral contraceptive use in the source population: controls will be older than the source population because patients with myocardial infarction tend to be older. This has several implications. A crude analysis of the data will produce odds ratios that are usually biased towards unity if the matching factor is associated with the exposure. The solution is to perform a matched or stratified analysis (see [item 12d][Explanation 12d Cross-sectional]). In addition, because the matched control group ceases to be representative for the population at large, the exposure distribution among the controls can no longer be used to estimate the population attributable fraction (see [Box 7][Box 7. Measures of association, effect and impact]) [@cole1971]. Also, the effect of the matching factor can no longer be studied, and the search for well-matched controls can be cumbersome – making a design with a non-matched control group preferable because the non-matched controls will be easier to obtain and the control group can be larger. Overmatching is another problem, which may reduce the efficiency of matched case-control studies, and, in some situations, introduce bias. Information is lost and the power of the study is reduced if the matching variable is closely associated with the exposure. Then many individuals in the same matched sets will tend to have identical or similar levels of exposures and therefore not contribute relevant information. Matching will introduce irremediable bias if the matching variable is not a confounder but in the causal pathway between exposure and disease. For example, in vitro fertilization is associated with an increased risk of perinatal death, due to an increase in multiple births and low birth weight infants [@gissler1996]. Matching on plurality or birth weight will bias results towards the null, and this cannot be remedied in the analysis.  
</br>  
Matching is intuitively appealing, but the complexities involved have led methodologists to advise against routine matching in case-control studies. They recommend instead a careful and judicious consideration of each potential matching factor, recognizing that it could instead be measured and used as an adjustment variable without matching on it. In response, there has been a reduction in the number of matching factors employed, an increasing use of frequency matching, which avoids some of the problems discussed above, and more case-control studies with no matching at all [@gefeller1998]. Matching remains most desirable, or even necessary, when the distributions of the confounder (e.g., age) might differ radically between the unmatched comparison groups [@costanza1995; @sturmer2002; @vandenbroucke2007]  

</br></br>

## Field-specific guidance   
**Anti-microbial stewardship programs [@tacconelli2016]**  
-	Specify antimicrobial usage according to: type, dosage, duration and route of administration  
-	Provide information using defined daily dosages (DDDs) and, in addition, other definitions closer to local reality (packages, prescriptions). Provide justification for the measurement presented  
-	Address antimicrobial combinations  
-	Explain rationale for grouping of antimicrobials  
-	Define time at risk for antimicrobial exposure and for resistance development  
-	Provide definition of resistance, multidrug resistance, including pattern of co-resistance; whether studies performed to identify location or resistance eg, plasmid, chromosome, integron, transposon  
-	Definition of infection and/or colonisation. If not a validated reference, provide evidence of robustness of the new definition </br>

**Genetic association studies [@little2009]**  
-	Clearly define genetic exposures (genetic variants) using a widely-used nomenclature system. Identify variables likely to be associated with population stratification (confounding by ethnic origin) </br>

**Medical Abortion [@creinin2016]**  
-	Exposure: Detail the medications used, including dose(s) and route(s) of administration. If more than one medication is used, state the planned time interval between medications, preferably in hours  
-	Outcome: Define successful medical abortion (should most commonly be considered as successful expulsion of the intrauterine pregnancy without need for surgical intervention)  
-	Outcome: Define the types of medical abortion failure (e.g., ongoing pregnancy, incomplete abortion, participant symptoms). Continuing pregnancy should be defined as a viable pregnancy following treatment (to be differentiated from a non-viable [i.e., retained gestational sac] </br>

**Neonatal infections [@fitchett2016]**  
-	State criteria used to deﬁne clinically signiﬁcant organisms for each sample type </br>

**Nutritional data [@lachat2016]**  
-	Clearly deﬁne foods, food groups, nutrients, or other food components    
-	When using dietary patterns or indices, describe the methods to obtain them and their nutritional properties </br>

**Seroepidemiologic studies for influenza [@horby2017]**  
-	Describe illness definitions and methods for ascertaining the presence or absence of clinical illness in subjects  
-	Describe the potential for immunization (specify vaccine and timing of vaccination in relationship to collection of serum), if applicable, to affect the outcome measures  
-	Describe any known or potential immunological cross-reactivity that may bias the outcome measures </br>

**Response-driven sampling [@white2015]**  
-	State how recruiter–recruit relationship was tracked  </br>

**Routinely collected health data [@benchimol2015]**    
-	A complete list of codes and algorithms used to classify exposures, outcomes, confounders, and effect modiﬁers should be provided. If these cannot be reported, an explanation should be provided </br>

**Seroepidemiologic studies for influenza [@horby2017]**    
-	Describe any known or potential immunological cross* reactivity that may bias the outcome measures </br>

## Resources  
Do you know of any good guidance or resources related to this item? Suggest them via comments below, [Twitter](https://twitter.com/sharpmelk), [GitHub](https://github.com/sharpmel/STROBECourse), or [e-mail](mailto:melissaksharp@gmail.com).  
</br>

- Shrier, I., & Platt, R. W. (2008). Reducing bias through directed acyclic graphs. BMC Medical Research Methodology, 8(1), 70. https://doi.org/10.1186/1471-2288-8-70 [@shrier2008]  
- Students 4 Best Evidence. (2018). A beginner’s guide to confounding. In Students 4 Best Evidence. https://www.students4bestevidence.net/blog/2018/10/01/a-beginners-guide-to-confounding/ [@students4bestevidence2018]
- VanderWeele, T. J. (2019). Principles of confounder selection. European Journal of Epidemiology, 34(3), 211–219. https://doi.org/10.1007/s10654-019-00494-6 [ @vanderweele2019]