---
title: "10-Bias"
author: "Melissa K Sharp"
output: html_document
---

# Item 9: Bias 
3.9 – Methods: Bias (Week 3, Module 2)
3.9.1 – STROBE
The items from STROBE state that you should report: 
•	Describe any efforts to address potential sources of bias

3.9.2 – Objectives
Specific examples from QA:
•	ROSES-I 9.1: If relevant, describe efforts to control for the potential effect of immunization on estimates of outcomes

Nonspecific examples from QA:
•	STROME-ID 9.1: describe any eﬀ orts made to address discovery or ascertainment bias
•	strega9 (b) For quantitative outcome variables, specify if any investigation of potential bias resulting from pharmacotherapy was undertaken. If relevant, describe the nature and magnitude of the potential bias, and explain what approach was used to deal with this.
•	nut-9. Report how bias in dietary or nutritional assessment was addressed, e.g., misreporting, changes in habits as a result of being measured, or data imputation from other sources.
•	vet9 Describe any eﬀorts to address potential sources of bias due to confounding, selection, or information bias
