---
title: "11-QuantitativeVariables"
author: "Melissa K Sharp"
delete_merged_file: true
site: bookdown::bookdown_site
output:
  bookdown::gitbook:
    number_sections: false 
    includes: 
      after_body: disqus.html
bibliography: bibliography.bib
csl: apa-annotated.csl
link-citations: yes
edit: https://github.com/sharpmel/STROBECourse
---

# Methods: Quantitative variables (11)
> The items from STROBE state that you should report:   
-	Explain how quantitative variables were handled in the analyses. If applicable, describe which groupings were chosen, and why</br>

**Some key items to consider adding:** 
- If applicable, describe how effects of treatment were dealt with.

## Explanation
>Investigators make choices regarding how to collect and analyse quantitative data about exposures, effect modifiers and confounders. For example, they may group a continuous exposure variable to create a new categorical variable (see box 4). Grouping choices may have important consequences for later analyses.81,82 We advise that authors explain why and how they grouped quantitative data, including the number of categories, the cut-points, and category mean or median values. Whenever data are reported in tabular form, the counts of cases, controls, persons at risk, person-time at risk, etc. should be given for each category. Tables should not consist solely of effect-measure estimates or results of model fitting.</br>
Investigators might model an exposure as continuous in order to retain all the information. In making this choice, one needs to consider the nature of the relationship of the exposure to the outcome. As it may be wrong to assume a linear relation automatically, possible departures from linearity should be investigated. Authors could mention alternative models they explored during analyses (eg, using log transformation, quadratic terms or spline functions). Several methods exist for fitting a nonlinear relation between the exposure and outcome.82–84 Also, it may be informative to present both continuous and grouped analyses for a quantitative exposure of prime interest.</br>
In a recent survey, two thirds of epidemiological publications studied quantitative exposure variables.4 In 42 of 50 articles (84%) exposures were grouped into several ordered categories, but often without any stated rationale for the choices made. Fifteen articles used linear associations to model continuous exposure but only 2 reported checking for linearity. In another survey, of the psychological literature, dichotomization was justified in only 22 of 110 articles (20%).85</br>

## Example 
“Patients with a Glasgow Coma Scale less than 8 are considered to be seriously injured. A GCS of 9 or more indicates less serious brain injury. We examined the association of GCS in these two categories with the occurrence of death within 12 months from injury” [80].
</br></br>

## Field-specific guidance:
**Anti-microbial stewardship programs [@tacconelli2016]**
- 	Provide subgroup analyses for immunocompromised, surgical/medical patients and patients in intensive care units, if applicable </br>

**Nutritional data [@lachat2016]**
- Explain the categorization of dietary/nutritional data (e.g., use of N-tiles and handling of nonconsumers) and the choice of reference category, if applicable. </br>

**Seroepidemiologic studies for influenza [@horby2017]**
- Describe the serological assay’s limit of detection and how this limit is defined or calculated. Describe how samples with a result below or on the borderline of the limit were handled in the analysis
- Describe and justify the titer or other result used to define “seropositivity,” or the antibody titer change or change in other assay result used to define “seroconversion.” Avoid the term “seroconversion” unless referring to change from undetectable to detectable antibody level. Otherwise report the fold-rise in titer. Avoid the term “infection” but report “seroprevalence at a titer of ….”
-  If statements or inferences are made about protection from infection, describe what is known about the correlation between the assay results and protection from infection and illness