---
title: "11-StudySize"
author: "Melissa K Sharp"
output: html_document
---

# Item 10: Study Size 

The items from STROBE state that you should report: 
•	Explain how the study size was arrived at

The sample size needed for a study depends on many factors including the size of the model, distribution of the variables, amount of missing data, reliability of the variables, and strength of the relationships among the variables. 

3.10.2 – Objectives
Specific examples from QA
•	ROSES-I 10.1: Describe the baseline estimated seroprevalence at given antibody titers or incidence of infection and cite published literature to support these estimates

Nonspecific examples from QA:
•	STROME-ID 10.1: describe any unique restrictions placed on the study sample size
•	vet10 (a) Describe how the study size was arrived at for each relevant level of organization
•	vet10 (b) Describe how non-independence of measurements was incorporated into sample-size considerations, if applicable
•	vet10 (c) If a formal sample-size calculation was used, describe the parameters, assumptions, and methods that were used, including a justiﬁcation for the eﬀect size selected
