---
title: "14-DescriptiveData"
author: "Melissa K Sharp"
delete_merged_file: true
site: bookdown::bookdown_site
output:
  bookdown::gitbook:
    number_sections: false 
    includes: 
      after_body: disqus.html
bibliography: bibliography.bib
csl: apa-annotated.csl
link-citations: yes
edit: https://github.com/sharpmel/STROBECourse
---

# Results: Descriptive Data (14)
> The items from STROBE state that you should report: 
-	Give characteristics of study participants (e.g., demographic, clinical, social) and information on exposures and potential confounders
-	Indicate the number of participants with missing data for each variable of interest
-	Cohort study Summarize follow-up time (e.g., average and total amount)

**Some key items to consider adding:**  
- Give the distribution of the biomarker measurement (including mean, median, range and variance)  
- Average treatment duration for all groups  
- Any subjects that changed exposure status
- Numbers eligible for follow-up, numbers with completed follow-up and numbers remaining on treatment and/or in analysis at relevant time points during follow-up (eg, at yearly intervals). 
-	Summarize follow-up time (e.g, average and total amount), if appropriate to the study design  
- The use of tabular or graphical presentations of numbers exposed, outcomes and relative risks over time is encouraged
-	Unweighted sample size and percentages
- Estimated population proportions or means with estimated precision (e.g., 95% confidence interval)  

## Explanation 14a
> Readers need descriptions of study participants and their exposures to judge the generalizability of the findings. Information about potential confounders, including whether and how they were measured, influences judgments about study validity. We advise authors to summarize continuous variables for each study group by giving the mean and standard deviation, or when the data have an asymmetrical distribution, as is often the case, the median and percentile range (eg, 25th and 75th percentiles). Variables that make up a small number of ordered categories (such as stages of disease I to IV) should not be presented as continuous variables; it is preferable to give numbers and proportions for each category (see also box 4). In studies that compare groups, the descriptive characteristics and numbers should be given by group, as in the example above.
</br>
Inferential measures such as standard errors and confidence intervals should not be used to describe the variability of characteristics, and significance tests should be avoided in descriptive tables. Also, P values are not an appropriate criterion for selecting which confounders to adjust for in analysis; even small differences in a confounder that has a strong effect on the outcome can be important.144,145
</br>
In cohort studies, it may be useful to document how an exposure relates to other characteristics and potential confounders. Authors could present this information in a table with columns for participants in two or more exposure categories, which permits to judge the differences in confounders between these categories.
</br>
In case-control studies potential confounders cannot be judged by comparing cases and controls. Control persons represent the source population and will usually be different from the cases in many respects. For example, in a study of oral contraceptives and myocardial infarction, a sample of young women with infarction more often had risk factors for that disease, such as high serum cholesterol, smoking and a positive family history, than the control group.146 This does not influence the assessment of the effect of oral contraceptives, as long as the prescription of oral contraceptives was not guided by the presence of these risk factors - eg, because the risk factors were only established after the event (see also box 5). In case-control studies the equivalent of comparing exposed and non-exposed for the presence of potential confounders (as is done in cohorts) can be achieved by exploring the source population of the cases: if the control group is large enough and represents the source population, exposed and unexposed controls can be compared for potential confounders.121,147
</br>
## Example 14a


## Explanation 14b
> As missing data may bias or affect generalizability of results, authors should tell readers amounts of missing data for exposures, potential confounders, and other important characteristics of patients (see also item 12c and box 6). In a cohort study, authors should report the extent of loss to follow-up (with reasons), since incomplete follow-up may bias findings (see also items 12d and 13).148 We advise authors to use their tables and figures to enumerate amounts of missing data. 
</br>
## Example 14b

## Explanation 14c
> Readers need to know the duration and extent of follow- up for the available outcome data. Authors can present a summary of the average follow-up with either the mean or median follow-up time or both. The mean allows a reader to calculate the total number of person-years by multiplying it with the number of study participants. Authors also may present minimum and maximum times or percentiles of the distribution to show readers the spread of follow-up times. They may report total person-years of follow-up or some indication of the proportion of potential data that was captured. 148 All such information may be presented separately for participants in two or more exposure categories. Almost half of 132 articles in cancer journals (mostly cohort studies) did not give any summary of length of follow-up.37

## Example 14c  
“During the 4366 person-years of follow-up (median 5.4, maximum 8.3 years), 265 subjects were diagnosed as having dementia, including 202 with Alzheimer's disease” [149].

</br></br>
## Field-specific guidance  
**Anti-microbial stewardship programs [@tacconelli2016]**  
-	Specify among the exposure: previous stay in long-term care facilities, nursing home and other healthcare settings </br>

**Genetic association studies [@little2009]**  
-	STREGA14a Consider giving information by genotype.</br>

**Infectious disease molecular epidemiology [@field2014]**  
- Give information by strain type if appropriate, with use of standardised nomenclature </br>

**Neonatal infections [@fitchett2016]**  
-	Describe maternal infections (clinical or on screening—eg, group B streptococcus or HIV) or risk factors for infection (eg, premature rupture of membranes, peripartum fever)  
-	Describe key neonatal characteristics, including sex, postnatal and gestational age categories (range and median), birthweight categories (range and median), birth place, feeding (breastmilk or other), and comorbidities  
-	Report data on occurrence of individual signs, according to case deﬁnitions  
-	Give proportion of mothers and neonates with peripartum antibiotic exposure (with or without pre-admission exposusure for neonates). Report details of antimicrobial drugs (or supportive care) given during the study </br> 

**Nutritional data [@lachat2016]**  
-	Give the distribution of participant characteristics across the exposure variables if applicable. Specify if food consumption of total population or consumers only were used to obtain results. </br> 

**Simulation-based research [@cheng2016]**  
-	In describing characteristics of study participants, include their previous experience with simulation and other relevant features as related to the intervention(s). </br>

**Veterinary epidemiology [@oconnor2016]**  
-	Give characteristics of study participants (e.g, demographic, clinical, social) and information on exposures and potential confounders by group and level of organization, if applicable   
-	Indicate number of participants with missing data for each variable of interest and at all relevant levels of organization</br>