---
title: "15-OutcomeData"
author: "Melissa K Sharp"
delete_merged_file: true
site: bookdown::bookdown_site
output:
  bookdown::gitbook:
    number_sections: false 
    includes: 
      after_body: disqus.html
bibliography: bibliography.bib
csl: vancouver.csl
link-citations: yes
edit: https://github.com/sharpmel/STROBECourse
---

# Results: Outcome Data (15)
The items from STROBE state that you should report: 
•	Cohort study Report numbers of outcome events or summary measures over time
•	Case-control study Report numbers in each exposure category, or summary measures of exposure
•	Cross-sectional study Report numbers of outcome events or summary measures

**Explanation [@vandenbroucke2007]**</br>
Before addressing the possible association between
exposures (risk factors) and outcomes, authors should report
relevant descriptive data. It may be possible and meaningful
to present measures of association in the same table that
presents the descriptive data (see item 14a). In a cohort study
with events as outcomes, report the numbers of events for
each outcome of interest. Consider reporting the event rate
per person-year of follow-up. If the risk of an event changes
over follow-up time, present the numbers and rates of events
in appropriate intervals of follow-up or as a Kaplan-Meier life
table or plot. It might be preferable to show plots as cumulative
incidence that go up from 0% rather than down from
100%, especially if the event rate is lower than, say, 30%.153
Consider presenting such information separately for participants
in different exposure categories of interest. If a cohort
study is investigating other time-related outcomes (eg, quantitative
disease markers such as blood pressure), present
appropriate summary measures (eg, means and standard deviations)
over time, perhaps in a table or figure.
For cross-sectional studies, we recommend presenting the
same type of information on prevalent outcome events or summary
measures. For case-control studies, the focus will be on
reporting exposures separately for cases and controls as frequencies
or quantitative summaries.154 For all designs, it may be
helpful also to tabulate continuous outcomes or exposures in
categories, even if the data are not analyzed as such.

<h2> Field-specific guidance:</h2>
•	STREGA15 cohort Report outcomes (phenotypes) for each genotype category over time
•	STREGA15c-c Report numbers in each genotype category
•	STREGA15 cross-sectional Report outcomes (phenotypes) for each genotype category
•	STROBE-NI 15.1: report the number (and the proportion) of samples microbiologically tested (including lumbar punctures for meningitis cases); the number (and the proportion) that were positive (including thresholds for detection, where applicable); all isolates obtained (including clinically signiﬁcant and nonsigniﬁcant); and antimicrobial susceptibilities of pathogens, where done
•	STROBE-NI 15.2: report the number (and the proportion) of babies with microbiologically proven infection (and number of infections per baby), and include this in the ﬂ ow chart (see ﬁgure 2)
•	STROBE-NI 15.3: report infections by day, for days 0–6. State age categories, if used, deﬁning early-onset and late-onset infection (eg, <72 h and ≥72 h, respectively)
•	STROBE-NI 15.4: report deaths and any subanalyses by risk groups

Nonspecific examples from QA:
•	EULAR Consider the use of a tabular or graphical presentation (Kaplan–Meier, cumulative incidence plot) of the outcome over time for the exposed and comparison cohort
•	VET15 (a) Report outcomes as appropriate for the study design and summarize at all relevant levels of organization
•	VET15 (b) For proportions and rates, report the numerator and denominator
•	VET15 (c) For continuous outcomes, report the number of observations and a measure of variability
