---
title: "16-MainResults"
author: "Melissa K Sharp"
delete_merged_file: true
site: bookdown::bookdown_site
output:
  bookdown::gitbook:
    number_sections: false 
    includes: 
      after_body: disqus.html
bibliography: bibliography.bib
csl: apa-annotated.csl
link-citations: yes
edit: https://github.com/sharpmel/STROBECourse
---

# Results: Main Results (16) 
> The items from STROBE state that you should report: 
-	Give unadjusted estimates and, if applicable, confounder-adjusted estimates and their precision (e.g., 95% confidence interval). Make clear which confounders were adjusted for and why they were included
-	Report category boundaries when continuous variables were categorized
-	If relevant, consider translating estimates of relative risk into absolute risk for a meaningful time period

**Some key items to consider adding:**</br>
-	 Present both relative risks and absolute measures such as event rates per person-time, risk differences or numbers needed to treat/numbers needed to harm   
-	Present results per time period of follow-up, if applicable, so as to indicate any time dependence of the association between exposure and outcome  
-	Report methods to standardize the results from the study sample to the target population  
-	For assessments involving >1 rater, interrater reliability should be reported  
- Give unadjusted estimates and, if applicable, adjusted estimates and their precision (e.g, 95% conﬁdence interval). Make clear which confounders and interactions were adjusted. Report all relevant parameters that were part of the model  
-	Report results of any adjustments for multiple comparisons  
</br>

## Explanation  
> In many situations, authors may present the results of unadjusted or minimally adjusted analyses and those from fully adjusted analyses. We advise giving the unadjusted analyses together with the main data, for example the number of cases and controls that were exposed or not. This allows the reader to understand the data behind the measures of association (see also item 15). For adjusted analyses, report the number of persons in the analysis, as this number may differ because of missing values in covariates (see also item 12c). Estimates should be given with confidence intervals. Readers can compare unadjusted measures of association with those adjusted for potential confounders and judge by how much, and in what direction, they changed.  
</br>
Readers may think that ‘adjusted’ results equal the causal part of the measure of association, but adjusted results are not necessarily free of random sampling error, selection bias, information bias, or residual confounding (see box 5). Thus, great care should be exercised when interpreting adjusted results, as the validity of results often depends crucially on complete knowledge of important confounders, their precise measurement, and appropriate specification in the statistical model (see also item 20).157,158 Authors should explain all potential confounders considered, and the criteria for excluding or including variables in statistical models. Decisions about excluding or including variables should be guided by knowledge, or explicit assumptions, on causal relations. Inappropriate decisions may introduce bias, for example by including variables that are in the causal pathway between exposure and disease (unless the aim is to asses how much of the effect is carried by the intermediary variable). If the decision to include a variable in the model was based on the change in the estimate, it is important to report what change was considered sufficiently important to justify its inclusion. If a ‘backward deletion’ or ‘forward inclusion’ strategy was used to select confounders, explain that process and give the significance level for rejecting the null hypothesis of no confounding. Of note, we and others do not advise selecting confounders based solely on statistical significance testing.147,159,160  
</br>
Recent studies of the quality of reporting of epidemiological studies found that confidence intervals were reported in most articles.4 However, few authors explained their choice of confounding variables.4,5 

## Explanation 16b  
> Categorizing continuous data has several important implications for analysis (see box 4) and also affects the presentation of results. In tables, outcomes should be given for each exposure category, for example as counts of persons at risk, person-time at risk, if relevant separately for each group (eg, cases and controls). Details of the categories used may aid comparison of studies and meta-analysis. If data were grouped using conventional cut-points, such as body mass index thresholds, 162 group boundaries (ie, range of values) can be derived easily, except for the highest and lowest categories. If quantilederived categories are used, the category boundaries cannot be inferred from the data. As a minimum, authors should report the category boundaries; it is helpful also to report the range of the data and the mean or median values within categories. 

## Example 


## Explanation 16c 
> The results from studies examining the association between an exposure and a disease are commonly reported in relative terms, as ratios of risks, rates or odds (see box 8).  
</br>
Relative measures capture the strength of the association between an exposure and disease. If the relative risk is a long way from 1 it is less likely that the association is due to confounding. 164,165 Relative effects or associations tend to be more consistent across studies and populations than absolute measures, but what often tends to be the case may be irrelevant in a particular instance. For example, similar relative risks were obtained for the classic cardiovascular risk factors for men living in Northern Ireland, France, the USA and Germany, despite the fact that the underlying risk of coronary heart disease varies substantially between these countries.166,167 In contrast, in a study of hypertension as a risk factor for cardiovascular disease mortality, the data were more compatible with a constant rate difference than with a constant rate ratio.168  
</br>
Widely used statistical models, including logistic169 and proportional hazards (Cox) regression 170 are based on ratio measures. In these models, only departures from constancy of ratio effect measures are easily discerned. Nevertheless, measures which assess departures from additivity of risk differences, such as the Relative Excess Risk from Interaction (RERI, see item 12b and box 8), can be estimated in models based on ratio measures.  
</br> 
In many circumstances, the absolute risk associated with an exposure is of greater interest than the relative risk. For example, if the focus is on adverse effects of a drug, one will want to know the number of additional cases per unit time of use (eg, days, weeks, or years). The example gives the additional number of breast cancer cases per 1000 women who used hormone-replacement therapy for 10 years.163 Measures such as the attributable risk or population attributable fraction may be useful to gauge how much disease can be prevented if the exposure is eliminated. They should preferably be presented together with a measure of statistical uncertainty (eg, confidence intervals, as in the example). Authors should be aware of the strong assumptions made in this context, including a causal relationship between a risk factor and disease (also see box 7).171 Because of the semantic ambiguity and complexities involved, authors should report in detail what methods were used to calculate attributable risks, ideally giving the formulae used.172  
</br>
A recent survey of abstracts of 222 articles published in leading medical journals found that in 62% of abstracts of randomized trials including a ratio measure absolute risks were given, but only in 21% of abstracts of cohort studies.173 A free text search of Medline 1966 to 1997 showed that 619 items mentioned attributable risks in the title or abstract, compared to 18,955 using relative risk or odds ratio, for a ratio of 1 to 31.174 [@vandenbroucke2007]  
</br> 

## Example  

Table.

Relative Rates of Rehospitalisation by Treatment in Patients in Community Care after First Hospitalisation due to Schizophrenia and Schizoaffective Disorder

https://doi.org/10.1371/journal.pmed.0040297.t008

## Box 7. Measures of association, effect and impact
**Measures of association, effect and impact**  
Observational studies may be solely done to describe the magnitude and distribution of a health problem in the population. They may examine the number of people who have a disease at a particular time (prevalence), or that develop a disease over a defined period (incidence). The incidence may be expressed as the proportion of people developing the disease (cumulative incidence) or as a rate per person-time of follow-up (incidence rate). Specific terms are used to describe different incidences; amongst others, mortality rate, birth rate, attack rate, or case fatality rate. Similarly, terms like point prevalence and period, annual or lifetime prevalence are used to describe different types of prevalence [@last2000].  
</br> 
Other observational studies address cause-effect relationships. Their focus is the comparison of the risk, rate or prevalence of the event of interest between those exposed and those not exposed to the risk factor under investigation. These studies often estimate a ‘relative risk', which may stand for risk ratios (ratios of cumulative incidences) as well as rate ratios (ratios of incidence rates). In case-control studies only a fraction of the source population (the controls) are included. Results are expressed as the ratio of the odds of exposure among cases and controls. This odds ratio provides an estimate of the risk or rate ratio depending on the sampling of cases and controls (see also Box 1) [175,176]. The prevalence ratio or prevalence odds ratio from cross-sectional studies may be useful in some situations [177].  
</br> 
Expressing results both in relative and absolute terms may often be helpful. For example, in a study of male British doctors the incidence rate of death from lung cancer over 50 years of follow-up was 249 per 100,000 per year among smokers, compared to 17 per 100,000 per year among non-smokers: a rate ratio of 14.6 (249/17) [178]. For coronary heart disease (CHD), the corresponding rates were 1001 and 619 per 100,000 per year, for a rate ratio of 1.61 (1001/619). The effect of smoking on death appears much stronger for lung cancer than for CHD. The picture changes when we consider the absolute effects of smoking. The difference in incidence rates was 232 per 100,000 per year (249 − 17) for lung cancer and 382 for CHD (1001 − 619). Therefore, among doctors who smoked, smoking was more likely to cause death from CHD than from lung cancer.  
</br> 
How much of the disease burden in a population could be prevented by eliminating an exposure? Global estimates have been published for smoking: according to one study 91% of all lung cancers, 40% of CHD and 33% of all deaths among men in 2000 were attributed to smoking [179]. The population attributable fraction is generally defined as the proportion of cases caused by a particular exposure, but several concepts (and no unified terminology) exist, and incorrect approaches to adjust for other factors are sometimes used [172,180]. What are the implications for reporting? The relative measures emphasise the strength of an association, and are most useful in etiologic research. If a causal relationship with an exposure is documented and associations are interpreted as effects, estimates of relative risk may be translated into suitable measures of absolute risk in order to gauge the possible impact of public health policies (see item 16c) [181]. However, authors should be aware of the strong assumptions made in this context [171]. Care is needed in deciding which concept and method is appropriate for a particular situation.  
</br></br>  

## Field-specific guidance  
**Infectious disease molecular epidemiology [@field2014]**  
- Consider showing molecular relatedness of strain types by means of a dendrogram or phylogenetic tree  </br>

**Medical abortion [@creinin2016]**  
- Present treatment success for each cohort and by gestational age  
- Present continuing pregnancies for each cohort and by gestational age  
- Present reasons for surgical intervention other than continuing pregnancy for each cohort and by gestational age  </br>

**Neonatal infections [@fitchett2016]**  
- For incidence, give risk per 1000 livebirths, or if alternative denominator used (eg, total births or bed days), deﬁne this clearly  </br>

**Nutritional data [@lachat2016]**  
- Specify if nutrient intakes are reported with or without inclusion of dietary supplement intake, if applicable  </br>

**Seroepidemiologic studies for influenza [@horby2017]**  
- Report unadjusted estimates of distribution of titers by age group  </br>

## Resources  
Do you know of any good guidance or resources related to this item? Suggest them via comments below, [Twitter](https://twitter.com/sharpmelk), [GitHub](https://github.com/sharpmel/STROBECourse), or [e-mail](mailto:melissaksharp@gmail.com).  
