---
title: "21-Generalizability"
author: "Melissa K Sharp"
delete_merged_file: true
site: bookdown::bookdown_site
output:
  bookdown::gitbook:
    number_sections: false 
    includes: 
      after_body: disqus.html
bibliography: bibliography.bib
csl: apa-annotated.csl
link-citations: yes
edit: https://github.com/sharpmel/STROBECourse
---

# Discussion: Generalizability (21)
> The items from STROBE state that you should report: 
-	Discuss the generalizability (external validity) of the study results

## Explanation and Elaboration [@vandenbroucke2007]
> Explanation
Generalizability, also called external validity or applicability, is the extent to which the results of a study can
be applied to other circumstances.216 There is no external validity per se; the term is meaningful only with regard to
clearly specified conditions.217 Can results be applied toan
individual, groups or populations that differ from those enrolled in the study with regard to age, sex, ethnicity,
severity of disease, and co-morbid conditions? Are the nature and level of exposures comparable, and the definitions
of outcomes relevant to another setting or population? 
</br>
Are data that were collected in longitudinal studies many years ago still relevant today? Are results from health services research in one country applicable to health systems in other countries? 
</br>
The question of whether the results of a study have external validity is often a matter of judgment that depends on the study setting, the characteristics of the participants, the exposures examined, and the outcomes assessed. Thus, it is crucial that authors provide readers with adequate information about the setting and locations, eligibility criteria, the exposures and how they were measured, the definition of outcomes, and the period of recruitment and follow-up. The degree of nonparticipation and the proportion of unexposed participants in whom the outcome develops are also relevant. Knowledge of the absolute risk and prevalence of the exposure, which will often vary across populations, are helpful when applying results to other settings and populations (see box 7).
</br>
Example</br>
“How applicable are our estimates to other HIV-1-infected patients? This is an important question because the
accuracy of prognostic models tends to be lower when applied to data other than those used to develop them. We
addressed this issue by penalising model complexity, and by choosing models that generalized best to cohorts omitted
from the estimation procedure. Our database included patients from many countries from Europe and North America, who were treated in different settings. The range of patients was broad: men and women, from teenagers to elderly people
were included, and the major exposure categories were well represented. The severity of immunodeficiency at baseline
ranged from not measureable to very severe, and viral load
from undetectable to extremely high.”215

<h2> Field-specific guidance:</h2>
**Anti-microbial stewardship programs [@tacconelli2016]**
- Discuss study setting, type of hospital, local epidemiology for the generalisability

*Simulation-based research [@cheng2016]**
- Describe generalizability of simulation-based outcomes to patient-based outcomes (if applicable).