---
title: "22-Funding"
author: "Melissa K Sharp"
delete_merged_file: true
site: bookdown::bookdown_site
output:
  bookdown::gitbook:
    number_sections: false 
    includes: 
      after_body: disqus.html
      in_header: analytics.html
bibliography: bibliography.bib
csl: apa-annotated.csl
link-citations: yes
edit: https://github.com/sharpmel/STROBECourse
---

# Other: Funding  
> The items from STROBE state that you should report:  
-	Give the source of funding and the role of the funders for the present study and, if applicable, for the original study on which the present article is based  
</br>

## Explanation  
> Some journals require authors to disclose the presence or absence of financial and other conflicts of interest.[@icmje1997; @krimsky2001] Several investigations show strong associations between the source of funding and the conclusions of research articles. [@bekelman2003; @davidson1986; stelfox1998; @lexchin2003] The conclusions in randomized trials recommended the experimental drug as the drug of choice much more often (odds ratio 5.3) if the trial was funded by for-profit organisations, even after adjustment for the effect size.[@alsnielsen2003] Other studies document the influence of the tobacco and telecommunication industries on the research they funded.[@barnes1998; barnes1996; @huss2007; @safer2002] There are also examples of undue influence when the sponsor is governmental or a nonprofit organization.  
</br>
Authors or funders may have conflicts of interest that influence any of the following: the design of the study [@safer2002]; choice of exposures,[@safer2002; @aspinall1995] outcomes,[@chan2004] statistical methods, [@melander2003] and selective publication of outcomes [@chan2004] and studies. [@scherer2005] Consequently, the role of the funders should be described in detail: in what part of the study they took direct responsibility (eg, design, data collection, analysis, drafting of the manuscript, decision to publish).[@icmje1997] Other sources of undue influence include employers (eg, university administrators for academic researchers and government supervisors, especially political appointees, for government researchers), advisory committees, litigants, and special interest groups.  
</br> 
  
## Resources  
Do you know of any good guidance or resources related to this item? Suggest them via comments below, [Twitter](https://twitter.com/sharpmelk), [GitHub](https://github.com/sharpmel/STROBECourse), or [e-mail](mailto:melissaksharp@gmail.com).
</br> 