---
title: "References"
author: "Melissa K Sharp"
delete_merged_file: true
site: bookdown::bookdown_site
output:
  bookdown::gitbook:
    number_sections: false 
    includes: 
      after_body: disqus.html
edit: https://github.com/sharpmel/STROBECourse
bibliography: bibliography.bib
csl: apa-annotated.csl
link-citations: yes
---

# Books
**Introductory textbooks**
- Dicker, R. C., Coronado, F., Koo, D., & Parrish, R. G. (2006). Principles of epidemiology in public health practice; an introduction to applied epidemiology and biostatistics. 3rd ed. https://stacks.cdc.gov/view/cdc/6914
- Rothman, K. J. (2012). Epidemiology: an introduction, 2nd edition. Oxford University Press.
Note. Dr Kenneth Rothman provides the rationale for this introductory textbook on this podcast: 
https://seriousepi.blubrry.net/2021/09/07/s2e1-modern-epidemiology-an-interview-with-dr-kenneth-rothman/
- Webb, P., Bain, C., & Page, A. (2019). Essential epidemiology: an introduction for students and health professionals, 4th edition. Cambridge University Press.

**Advanced textbooks**
Lash, T. J., VanderWheele, T. J., Haneuse, S., & Rothman, K. J. Modern Epidemiology, 4th edition. Wolters Kluwer, 2021
Note. Dr Kenneth Rothman discusses the history of this book in this podcast episode: 
https://seriousepi.blubrry.net/2021/09/07/s2e1-modern-epidemiology-an-interview-with-dr-kenneth-rothman/

# Online Learning Modules
- Boston University School of Public Health. MPH Online Learning Modules. Retrieved February 13, 2020, from http://sphweb.bumc.bu.edu/otlt/MPH-Modules/Menu/index.html [@busph2020]  
- Johns Hopkins Bloomberg School of Public Health. Fundamentals of Epidemiology I : Lecture Materials. In JHSPH OpenCourseWare. Retrieved January 27, 2020, from http://ocw.jhsph.edu/index.cfm/go/viewCourse/course/FundEpi/coursePage/lectureNotes/ [@hopkins2020]

# Online groups
- The STRATOS (STRengthening Analytical Thinking for Observational Studies) Initiative: https://stratos-initiative.org/
Note: The background for this group is described in Sauerbrei, W., Abrahamowicz, M., Altman, D. G., le Cessie, S., Carpenter, J., & STRATOS initiative. (2014). STRengthening analytical thinking for observational studies: the STRATOS initiative. Statistics in medicine, 33(30), 5413-5432.

# Online journal articles with educational aims
- International Journal of Epidemiology: The Education Corner. (2022). Retrieved September 10, 2022, from https://academic.oup.com/ije/pages/Education_Corner

# Definitional issues
Frérot, M., Lefebvre, A., Aho, S., Callier, P., Astruc, K., & Aho Glélé, L. S. (2018). What is epidemiology? Changing definitions of epidemiology 1978-2017. PloS one, 13(12), e0208442.

</br> 

## Writing Resources
**Writing Aid Tool**  
- Lachat, C. (2019). Contribute to carllachat/WritingAidTool development by creating an account on GitHub. https://github.com/carllachat/WritingAidTool
original-date: 2019-02-07T17:29:24Z [@lachat2019]  
- Hawwash, D., Sharp, M. K., Argaw, A., Kolsteren, P., & Lachat, C. (2019). Usefulness of applying research reporting guidelines as Writing Aid software: A crossover randomised controlled trial. BMJ Open, 9(11). https://doi.org/10.1136/bmjopen-2019-030943 [@hawwash2019]  

</br> 

**Others**  
- Perneger, T. V., & Hudelson, P. M. (2004). Writing a research article: Advice to beginners. International Journal for Quality in Health Care, 16(3), 191–192. https://doi.org/10.1093/intqhc/mzh053 [@perneger2004]  
</br> 

## Teaching Epidemiology  
- Trichopolous, D. (Ed.). (2010). Teaching epidemiology: A guide for teachers in epidemiology, public health and clinical medicine. Oxford University Press. https://www.amazon.co.uk/Teaching-Epidemiology-Teachers-Clinical-Medicine/dp/0199239479 [@trichopolous2010]  
- Keyes, K. M., & Galea, S. (2014). Current Practices in Teaching Introductory Epidemiology: How We Got Here, Where to Go. American Journal of Epidemiology, 180(7), 661–668. https://doi.org/10.1093/aje/kwu219 [@keyes2014]
- Pai Global TB Group. (2022). TeachEpi. Toronto, Canada: McGill University. https://www.teachepi.org/

## Podcasts
Society for Epidemiological Research (SER). (2022). SERious Epi. Retrieved on September 10, 2022 from https://seriousepi.blubrry.net/
Society for Epidemiological Research (SER). (2022). Epidemiology counts: Retrieved on September 10, 2022 from https://serepidemiologycounts.blubrry.net/
McGowan, L. D., & Murray, E. (2022). Casual Inference. Retrieved on September 10, 2022 from https://casualinfer.libsyn.com/

</br> 

## Statistics and Coding
- BMJ Statistics Notes. Retrieved September 10, 2022, from https://www.bmj.com/specialties/statistics-notes
- Datamethods Discussion Forum. Retrieved February 13, 2020, from  https://discourse.datamethods.org/ [@datamethods2020]
- JAMA Network Guide to Statistics and Medicine. Retrieved September 10, 2022, from https://jamanetwork.com/collections/44042/guide-to-statistics-and-medicine
- Stack Overflow - Where Developers Learn, Share, & Build Careers. In Stack Overflow. Retrieved February 13, 2020, from https://stackoverflow.com/ [@stackoverflow2020]  

</br> 

## Resources  
Do you know of any good guidance or resources related to this item? Suggest them via comments below, [Twitter](https://twitter.com/sharpmelk), [GitHub](https://github.com/sharpmel/STROBECourse), or [e-mail](mailto:melissaksharp@gmail.com).
</br> 
